--- #YAML:1.0
name:                Win32-GUI-OpenGLFrame
version:             0.02
abstract:            Integrate OpenGL with Win32::GUI
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    OpenGL:                        0
    Win32::GUI:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Robert May <robertmay@cpan.org>
